Bugfix: Avoid shadowing of builtin exit() function
This was not mission critical since the builtin exit() function
was only used to terminate the program when wrong input parameters
were given. Still...

This was the traceback:

   Traceback (most recent call last):
     File "/home/lemoer/documents/ff/git/wireguard-vxlan-glue/netlink.py", line 228, in <module>
       exit(1)
   TypeError: 'Event' object is not callable

Fixes 097545a240eec2a4b14d1ab768f060b08d2dc169